import './globals.css';
import { raleway } from './fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`lg:w-[75%] m-auto p-5 ${raleway.className}`}>
      <body>{children}</body>
    </html>
  );
}
