import './globals.css';
import { raleway } from './fonts';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} debug-screens flex flex-col min-h-screen`}
      >
        <Navbar />
        <main className="p-5 grow xl:w-[90%] 2xl:w-[75%] lg:mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
